version: '3.8'

services:
  mongo:
    image: mongo:latest  # Using official MongoDB image
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db  
      - ./mongo_init:/docker-entrypoint-initdb.d  
   

    restart: always