global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "fastapi"
    static_configs:
      - targets: ["fastapi:8000"]

    metrics_path: "/metrics"

    
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "node_exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: 'qdrant'
    static_config:
      - targets: ["qdarnt:6333"]

    metrics_path: '/metrics'

 